### ISSUE TITLE
It recognizes the tracks but I cannot select them

### ISSUE THREAD

**Issue by pmansito** [Huracan-project/huracanpy#37]
Mac mini M1 (Sonoma 14.6.1)

> python
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import huracanpy
>>> tracks = huracanpy.load("../ophelia.csv")
>>> minimal_tracks = tracks[["track_id", "time", "lat", "lon"]]
>>> print(minimal_tracks)
<xarray.Dataset>
Dimensions:   (record: 46)
Coordinates:
  * record    (record) int64 0 1 2 3 4 5 6 7 8 9 ... 37 38 39 40 41 42 43 44 45
Data variables:
    track_id  (record) object 'AL172017' 'AL172017' ... 'AL172017' 'AL172017'
    time      (record) datetime64[ns] 2017-10-06T12:00:00 ... 2017-10-17T18:0...
    lat       (record) float64 31.8 32.3 32.9 32.7 32.3 ... 57.3 58.7 59.3 60.1
    lon       (record) float64 320.5 321.4 322.7 321.5 ... 353.9 357.1 1.5 5.3
>>> track_groups = tracks.groupby("track_id")
>>> track_groups
DatasetGroupBy, grouped over 'track_id'
1 groups with labels 'AL172017'.
>>> track_id1 = track_groups[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/miniconda3/envs/cps/lib/python3.11/site-packages/xarray/core/groupby.py", line 804, in __getitem__
    return self._obj.isel({self._group_dim: self.groups[key]})
                                            ~~~~~~~~~~~^^^^^
KeyError: 1
>>> track_id1 = track_groups[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/miniconda3/envs/cps/lib/python3.11/site-packages/xarray/core/groupby.py", line 804, in __getitem__
    return self._obj.isel({self._group_dim: self.groups[key]})
                                            ~~~~~~~~~~~^^^^^
KeyError: 0

**Comment by stella-bourdin** [comment]
I think this has to do with the way xarray grouping works, not really hurcanpy. You can access your group with track_groups["AL172017"], as the labels are the grouping values. I do not think xarray supports integer index for groups.

**Comment by pmansito** [comment]
Yes, it works with using the track_id instead of using the index:

>>> track_id1 = track_groups['AL172017']
>>> track_id1
<xarray.Dataset>
Dimensions:   (record: 46)
Coordinates:
  * record    (record) int64 0 1 2 3 4 5 6 7 8 9 ... 37 38 39 40 41 42 43 44 45
Data variables: (12/15)
    track_id  (record) object 'AL172017' 'AL172017' ... 'AL172017' 'AL172017'
    name      (record) object 'OPHELIA' 'OPHELIA' ... 'OPHELIA' 'OPHELIA'
    n         (record) int64 47 47 47 47 47 47 47 47 ... 47 47 47 47 47 47 47 47
    null1     (record) float64 nan nan nan nan nan nan ... nan nan nan nan nan
    year      (record) int64 2017 2017 2017 2017 2017 ... 2017 2017 2017 2017
    month     (record) int64 10 10 10 10 10 10 10 10 ... 10 10 10 10 10 10 10 10
    ...        ...
    sec       (record) int64 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0
    null2     (record) float64 nan nan nan nan nan nan ... nan nan nan nan nan
    type      (record) object 'LO' 'LO' 'LO' 'LO' 'LO' ... 'EX' 'EX' 'EX' 'EX'
    lat       (record) float64 31.8 32.3 32.9 32.7 32.3 ... 57.3 58.7 59.3 60.1
    lon       (record) float64 320.5 321.4 322.7 321.5 ... 353.9 357.1 1.5 5.3
    time      (record) datetime64[ns] 2017-10-06T12:00:00 ... 2017-10-17T18:0...

Time to update the documentation!
